/**
 * Fio banka's statement JSON → our normalized shapes.
 *
 * Fio's REST API (https://www.fio.cz/bankovni-sluzby/api-bankovnictvi) is a
 * token API: one read-only token per account, generated by the account holder
 * in internet banking, and no OAuth, redirect or consent expiry. Every
 * transaction field arrives as a numbered `columnN` object whose meaning is
 * fixed by the published column table, so the mapping below is a table lookup
 * rather than a guess.
 *
 * Pure and network-free on purpose: the HTTP call lives in `fio-adapter.ts`,
 * everything that decides what a row means lives here and is unit-tested.
 */
import type { ProviderAccount, ProviderTransaction } from "@/lib/bank/provider";
import { extractVariableSymbol, normalizeSymbol } from "@/lib/payment-matching";

/** Namespace for every Fio key written to `accounts.external_ref` and
 *  `transactions.external_id`. GoCardless refs are already stored bare, so a
 *  prefix is what keeps the two providers from colliding under the per-user
 *  unique indexes. */
export const FIO_PREFIX = "fio:";

export function fioAccountRef(accountId: string): string {
  return `${FIO_PREFIX}${accountId}`;
}

export function fioExternalId(movementId: string): string {
  return `${FIO_PREFIX}${movementId}`;
}

export type FioStatement = {
  account: ProviderAccount;
  transactions: ProviderTransaction[];
  /** Fio's own last-movement id, usable as a sync cursor. Null when absent. */
  lastId: string | null;
};

type FioColumn = { value: unknown } | null | undefined;

function columnValue(row: Record<string, unknown>, id: number): unknown {
  const cell = row[`column${id}`] as FioColumn;
  if (!cell || typeof cell !== "object") return null;
  return (cell as { value: unknown }).value ?? null;
}

function text(value: unknown): string | null {
  if (value === null || value === undefined) return null;
  const s = String(value).trim();
  return s.length > 0 ? s : null;
}

/** Fio dates arrive as "2026-01-05+0100"; only the calendar day is stored. */
function isoDate(value: unknown): string | null {
  const raw = text(value);
  if (!raw) return null;
  const match = raw.match(/^(\d{4})-(\d{2})-(\d{2})/);
  return match ? match[0] : null;
}

function amount(value: unknown): number | null {
  if (typeof value === "number") return Number.isFinite(value) ? value : null;
  const raw = text(value);
  if (!raw) return null;
  // A string amount may be Czech-formatted ("1 234,56").
  const cleaned = raw.replace(/\s/g, "").replace(",", ".");
  const parsed = Number(cleaned);
  return Number.isFinite(parsed) ? parsed : null;
}

/** The Czech variable symbol: column 5 when the bank filled it, otherwise
 *  scanned out of the free-text fields the same way the GoCardless mapper does. */
function variableSymbol(row: Record<string, unknown>): string | null {
  const explicit = text(columnValue(row, 5));
  if (explicit && /^\d{1,10}$/.test(explicit)) return normalizeSymbol(explicit);
  const candidates = [
    text(columnValue(row, 16)),
    text(columnValue(row, 7)),
    text(columnValue(row, 25)),
  ];
  for (const candidate of candidates) {
    if (!candidate) continue;
    const found = extractVariableSymbol(candidate);
    if (found) return found;
  }
  return null;
}

/**
 * The human-readable description. Fio spreads it over the recipient message,
 * the user identification, the counterparty name and the movement type, so the
 * first one that carries text wins and the rest are appended only when they add
 * something.
 */
function note(row: Record<string, unknown>): string | null {
  const parts = [
    text(columnValue(row, 16)),
    text(columnValue(row, 7)),
    text(columnValue(row, 10)),
    text(columnValue(row, 25)),
    text(columnValue(row, 8)),
  ].filter((part): part is string => part !== null);
  const seen = new Set<string>();
  const unique = parts.filter((part) => {
    const key = part.toLowerCase();
    if (seen.has(key)) return false;
    seen.add(key);
    return true;
  });
  if (unique.length === 0) return null;
  return unique.join(" · ").slice(0, 500);
}

/** One `transactionList.transaction[]` entry → a provider transaction, or null
 *  when the entry lacks the two fields a row cannot exist without. */
export function parseFioTransaction(
  entry: unknown,
  fallbackCurrency: string,
): ProviderTransaction | null {
  if (!entry || typeof entry !== "object") return null;
  const row = entry as Record<string, unknown>;
  const movementId = text(columnValue(row, 22));
  const occurredOn = isoDate(columnValue(row, 0));
  const raw = amount(columnValue(row, 1));
  if (!movementId || !occurredOn || raw === null) return null;
  return {
    kind: raw < 0 ? "expense" : "income",
    // The database enforces amount >= 0; direction lives in `kind`.
    amount: Math.abs(raw),
    currency: text(columnValue(row, 14)) ?? fallbackCurrency,
    category: null,
    note: note(row),
    occurred_on: occurredOn,
    external_id: fioExternalId(movementId),
    variable_symbol: variableSymbol(row),
  };
}

/**
 * A whole `transactions.json` payload. Returns null when the document is not a
 * Fio statement at all; a statement whose transaction list is empty or missing
 * is a valid, quiet result.
 */
export function parseFioStatement(
  payload: unknown,
  fallbackName: string | null = null,
): FioStatement | null {
  if (!payload || typeof payload !== "object") return null;
  const statement = (payload as Record<string, unknown>).accountStatement;
  if (!statement || typeof statement !== "object") return null;
  const info = (statement as Record<string, unknown>).info;
  if (!info || typeof info !== "object") return null;

  const infoRow = info as Record<string, unknown>;
  const accountId = text(infoRow.accountId);
  if (!accountId) return null;
  const currency = text(infoRow.currency) ?? "CZK";
  const closing = amount(infoRow.closingBalance);

  const listHolder = (statement as Record<string, unknown>).transactionList;
  const rawList =
    listHolder && typeof listHolder === "object"
      ? (listHolder as Record<string, unknown>).transaction
      : null;
  const entries = Array.isArray(rawList) ? rawList : [];

  const transactions = entries
    .map((entry) => parseFioTransaction(entry, currency))
    .filter((tx): tx is ProviderTransaction => tx !== null);

  const account: ProviderAccount = {
    accountRef: fioAccountRef(accountId),
    name: fallbackName ?? `Fio ${accountId}`,
    currency,
    balance: closing,
  };

  return { account, transactions, lastId: text(infoRow.idTo) };
}

/* --------------------------------- window --------------------------------- */

/** How far back a first pull reaches when no cursor exists yet. */
const INITIAL_WINDOW_DAYS = 90;
/** Re-read this many days before the cursor so a late booking is still seen. */
const OVERLAP_DAYS = 7;

function dayKey(date: Date): string {
  return date.toISOString().slice(0, 10);
}

function shiftDays(from: Date, days: number): Date {
  const next = new Date(from);
  next.setUTCDate(next.getUTCDate() + days);
  return next;
}

/**
 * The date range a pull covers: the cursor minus an overlap, or the initial
 * window when this connection has never synced. The overlap is what catches a
 * transaction Fio books a few days late; the dedupe on `external_id` makes the
 * repeat free.
 */
export function fioWindow(
  cursor: string | null,
  today: Date,
): { from: string; to: string } {
  const to = dayKey(today);
  if (cursor && /^\d{4}-\d{2}-\d{2}$/.test(cursor)) {
    const parsed = new Date(`${cursor}T00:00:00Z`);
    if (!Number.isNaN(parsed.getTime())) {
      return { from: dayKey(shiftDays(parsed, -OVERLAP_DAYS)), to };
    }
  }
  return { from: dayKey(shiftDays(today, -INITIAL_WINDOW_DAYS)), to };
}
