/** Official career destinations researched 2026-09-07. Not a list of open vacancies. */
export const CAREER_COMPANIES = [
  ["Apify", "https://apify.com/jobs", "Product"],
  [
    "Productboard",
    "https://www.productboard.com/careers/open-positions/",
    "Product",
  ],
  ["STRV", "https://www.strv.com/careers", "Agency"],
  ["Mews", "https://www.mews.com/en/careers", "Product"],
  ["Kiwi.com", "https://jobs.kiwi.com/teams/devs/", "Product"],
  ["Rohlik Group", "https://career.rohlik.group/group/list", "Commerce"],
  ["Rossum", "https://jobs.ashbyhq.com/rossum.ai", "Product"],
  ["Cookielab", "https://www.cookielab.io/careers", "Agency"],
  ["Ackee", "https://www.ackee.agency/career", "Agency"],
  ["Cleevio", "https://www.cleevio.com/careers", "Agency"],
  [
    "Outreach",
    "https://www.outreach.ai/company/working-at-outreach",
    "Product",
  ],
  ["SentinelOne", "https://www.sentinelone.com/jobs/", "Product"],
  ["Livesport", "https://www.livesport.eu/en/pridej-se-k-nam", "Product"],
  ["Shoptet", "https://kariera.shoptet.cz/", "Commerce"],
  ["Alza", "https://kariera.alza.cz/oddeleni/it/", "Commerce"],
  ["Komerční banka", "https://kariera.kb.cz/it-technology/a-121/", "Finance"],
  ["Air Bank", "https://kariera.airbank.cz/prehled-pozic", "Finance"],
  [
    "DHL IT Services",
    "https://careers.dhl.com/global/en/its-czech-republic",
    "Enterprise",
  ],
  ["Seznam.cz", "https://o-seznam.cz/kariera/praha/", "Product"],
  ["FTMO", "https://careers.ftmo.com/en/it-development/", "Finance"],
  [
    "Expedia Group",
    "https://careers.expediagroup.com/locations/prague-czechia/",
    "Product",
  ],
  ["Salsita", "https://salsita.ai/career", "Agency"],
  ["Qest technologies", "https://www.qest.cz/en/career", "Agency"],
  ["iQuest", "https://www.iquest.cz/cs/volne-pozice-vyvojari", "Agency"],
  [
    "Barclays",
    "https://search.jobs.barclays/location/prague-jobs/22545/3077311-3067695-3067696/4",
    "Finance",
  ],
  ["Avenga", "https://career.avenga.com/jobs?location=Prague&query=", "Agency"],
] as const;
