import type { ScrapedJob } from "./types";

/**
 * Leads selected by the owner for the September 2026 application session.
 *
 * These summaries keep the requirements needed for matching and letter
 * guidance without copying whole third-party job advertisements. The normal
 * visit-time availability check still decides whether a row is shown.
 */
export const CURATED_JOBS: ScrapedJob[] = [
  {
    source: "curated",
    externalId: "startupjobs-69505",
    title: "Remote Full-stack Developer (React + Node.js)",
    company: "Sudolabs Technologie",
    url: "https://www.startupjobs.cz/nabidka/69505/remote-full-stack-developer-react-node-js",
    location: "Czechia / Slovakia · remote",
    remote: true,
    role: "fullstack",
    salary: "€15–30/hour · up to 130,000 CZK/month",
    tags: ["TypeScript", "React", "Node.js", "remote", "product"],
    seniority: "Medior / Senior",
    postedAt: "2026-08-05T00:00:00.000Z",
    description:
      "Sudolabs is hiring a TypeScript full-stack developer resident in Czechia or Slovakia. The work combines React and Node.js in a three-to-five-person product team, with detailed code review, pair programming, estimation, delivery ownership, client or product-manager communication, and knowledge sharing. The role values product thinking, independent work, code quality, and learning. Full-time employment or trade licence; remote work is available.",
  },
  {
    source: "curated",
    externalId: "jobs-2001364422",
    title: "React vývojář",
    company: "Popron Systems · Veolia group",
    url: "https://www.popronsystems.cz/kariera/react-vyvojar/",
    location: "Praha 5 · hybrid",
    remote: false,
    role: "frontend",
    salary: null,
    tags: [
      "TypeScript",
      "React",
      "React Native",
      "REST API",
      "Figma",
      "PostgreSQL",
      "GCP",
    ],
    seniority: "1+ years",
    postedAt: null,
    description:
      "Popron Systems, part of the Veolia group, is hiring for its FLOWIO low-code platform in Prague. The role develops dynamic React web interfaces and React Native mobile features, reusable UI components, configurable forms and workflows, and REST integrations. It includes feature analysis, architecture decisions, design collaboration, code review, and responsibility for delivery quality. TypeScript and at least one year of React experience are required; component-library experience is useful. Czech at native level and hybrid work in Prague 5 are required.",
  },
  {
    source: "curated",
    externalId: "linkedin-4455898471",
    title: "Full Stack Engineer - EMEA",
    company: "Deel",
    url: "https://cz.linkedin.com/jobs/view/full-stack-engineer-emea-at-deel-4455898471",
    location: "Czechia · remote",
    remote: true,
    role: "fullstack",
    salary: null,
    tags: [
      "TypeScript",
      "JavaScript",
      "React",
      "Express.js",
      "Next.js",
      "NestJS",
      "PostgreSQL",
    ],
    seniority: "Mid-level · 4+ years",
    postedAt: "2026-09-01T00:00:00.000Z",
    description:
      "Deel is hiring an EMEA full-stack engineer for its global payroll and HR platform. The role owns features across client, server, services, and database: responsive React applications, TypeScript and JavaScript, Express APIs, functional components and hooks, tests, and PostgreSQL schemas and queries. Next.js, NestJS, and Vite are useful extras. The team works remote-first and expects at least four years of full-stack TypeScript experience, independent ownership, collaboration, testing, and product planning.",
  },
  {
    source: "curated",
    externalId: "linkedin-4420465535",
    title: "Front-End Developer",
    company: "Ubiquiti Inc.",
    url: "https://cz.linkedin.com/jobs/view/front-end-developer-at-ubiquiti-inc-4420465535",
    location: "Prague · hybrid",
    remote: false,
    role: "frontend",
    salary: null,
    tags: [
      "TypeScript",
      "React",
      "TanStack",
      "Vite",
      "WebSockets",
      "SSE",
      "Figma",
    ],
    seniority: "Mid-senior · 5+ years",
    postedAt: "2026-08-24T00:00:00.000Z",
    description:
      "Ubiquiti is hiring an experienced frontend developer for a greenfield Prague product. The stack is TypeScript, React, TanStack, and Vite, with an established UI component system and close Figma collaboration. The work covers architecture, polished user experience, real-time data through WebSockets, SSE and streaming updates, design tokens, browser performance, accessibility, and testing. The posting asks for five or more years of professional frontend experience and at least two office days per week in Prague.",
  },
  {
    source: "curated",
    externalId: "linkedin-4459384178",
    title: "Full Stack Product Engineer - Remote/Europe",
    company: "Jiga",
    url: "https://cz.linkedin.com/jobs/view/full-stack-product-engineer-remote-europe-at-jiga-4459384178",
    location: "Europe · remote",
    remote: true,
    role: "fullstack",
    salary: "$80,000–140,000/year",
    tags: ["React", "Node.js", "MongoDB", "remote", "product"],
    seniority: "3+ years",
    postedAt: "2026-09-03T00:00:00.000Z",
    description:
      "Jiga is seeking a Europe-based full-stack product engineer for a small, asynchronous remote team. The role owns product features and architecture end to end, from React interfaces to Node.js services and data modelling; MongoDB is useful. The company looks for at least three years building complex full-stack web products, product-company experience, strong delivery ownership, security, scaling, performance, maintainability, and some overlap with GMT+3. The application asks for a short personal introduction and a favourite ice-cream flavour.",
  },
  {
    source: "curated",
    externalId: "linkedin-4113901987",
    title: "Full Stack Software Engineer",
    company: "Lightdash",
    url: "https://cz.linkedin.com/jobs/view/full-stack-software-engineer-at-lightdash-4113901987",
    location: "Czechia · remote (GMT ±3)",
    remote: true,
    role: "fullstack",
    salary: "$100,000–170,000/year",
    tags: [
      "TypeScript",
      "React",
      "Node.js",
      "SQL",
      "Express.js",
      "Docker",
      "GCP",
      "open source",
    ],
    seniority: "Entry level",
    postedAt: null,
    description:
      "Lightdash is hiring a full-stack engineer for an open-source data product. Its primary stack is TypeScript, React, Node.js, SQL, Express, Docker, and Google Cloud. The role owns features from planning through deployment and iteration, works directly with users, reviews community issues, and occasionally creates or presents content. Lightdash values product design, clear remote communication, open-source interest, engineering culture, ownership, and residence within GMT plus or minus three hours. LinkedIn still shows an application action, although the listing age should be checked before investing in a long application.",
  },
  {
    source: "curated",
    externalId: "linkedin-4461473153",
    title: "Vývojář / developer / AI orchestrator",
    company: "ORGREZ DATA",
    url: "https://cz.linkedin.com/jobs/view/v%C3%BDvoj%C3%A1%C5%99-developer-ai-orchestrator-at-orgrez-data-s-r-o-4461473153",
    location: "Prague or Brno · hybrid",
    remote: false,
    role: "fullstack",
    salary: null,
    tags: [
      "TypeScript",
      "Node.js",
      "NestJS",
      "React",
      "Vite",
      "TailwindCSS",
      "PostgreSQL",
      "Prisma",
      "Redis",
      "Jest",
      "OpenAPI",
      "AI",
      "IoT",
    ],
    seniority: "Entry level · 2+ years backend",
    postedAt: "2026-09-06T00:00:00.000Z",
    description:
      "ORGREZ DATA builds software for energy, ESG reporting, cybersecurity, and AI-assisted workflows. This is a backend-leaning TypeScript role using Node.js, NestJS, PostgreSQL, Prisma, Redis or BullMQ, OpenAPI, Jest, Linux, and CI/CD, with occasional React, Vite, and Tailwind frontend work. It also covers LLM integrations, reviewed agent output, RAG and embeddings, and time-series or IoT data. The role asks for two or more years of Node.js and TypeScript backend practice, solid SQL and indexing, Czech or Slovak, and hybrid work from Prague or Brno.",
  },
  {
    source: "curated",
    externalId: "linkedin-4456013072",
    title: "Software Engineer - Frontend - Payments",
    company: "Kraken",
    url: "https://cz.linkedin.com/jobs/view/software-engineer-frontend-payments-at-kraken-4456013072",
    location: "Czechia · remote",
    remote: true,
    role: "frontend",
    salary: null,
    tags: [
      "JavaScript",
      "TypeScript",
      "React",
      "React Native",
      "Next.js",
      "REST API",
      "WebSockets",
      "payments",
      "fintech",
    ],
    seniority: "Senior · 5+ years",
    postedAt: "2026-08-24T00:00:00.000Z",
    description:
      "Kraken is hiring a senior frontend engineer for payment and blockchain transaction experiences. The role uses React.js, JavaScript and TypeScript, Next.js, REST APIs, WebSockets, frontend testing, and some React Native. It focuses on secure and reliable fund transfers, onboarding, payment-provider integrations, customer trust, fault tolerance, financial compliance, technical decisions, and mentoring. The posting asks for five or more years of software development and encourages strong candidates to apply even when they do not meet every requirement.",
  },
];

export async function fetchCuratedJobs(): Promise<ScrapedJob[]> {
  const observedAt = new Date().toISOString();
  return CURATED_JOBS.map((job) => ({ ...job, observedAt }));
}
